#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
GKT Baseline for MARS Paper

This is a lightweight Graph-based Knowledge Tracing baseline.

It uses:
1. Same train/test split generated by mars_experiments.py
2. Skill-level graph built from learner skill transitions
3. Graph propagation over skill states
4. GRU update for observed skill-response interaction
5. Next-response prediction using next skill state

Run:

python gkt_baseline.py \
  --train results/assistments_online_final/train_interactions.csv \
  --test results/assistments_online_final/test_interactions.csv \
  --out results/gkt_final \
  --batch_size 256 \
  --epochs 30 \
  --hidden_dim 128 \
  --emb_dim 128 \
  --amp \
  --compile
"""

import argparse
import logging
import random
import time
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd
from tqdm import tqdm

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader

from sklearn.metrics import roc_auc_score, accuracy_score, log_loss, brier_score_loss


# ---------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------

def setup_logger(out_dir=None):
    logger = logging.getLogger("GKT")
    logger.setLevel(logging.INFO)
    logger.propagate = False

    for handler in list(logger.handlers):
        logger.removeHandler(handler)
        handler.close()

    formatter = logging.Formatter(
        fmt="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    )

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

    if out_dir is not None:
        Path(out_dir).mkdir(parents=True, exist_ok=True)
        file_handler = logging.FileHandler(Path(out_dir) / "gkt_training.log")
        file_handler.setFormatter(formatter)
        logger.addHandler(file_handler)

    return logger


LOGGER = setup_logger()


class Timer:
    def __init__(self, message):
        self.message = message

    def __enter__(self):
        self.start = time.time()
        LOGGER.info(f"START: {self.message}")
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        elapsed = time.time() - self.start
        if exc_type is None:
            LOGGER.info(f"DONE: {self.message} | Time: {elapsed:.2f} sec")
        else:
            LOGGER.error(f"FAILED: {self.message} | Time: {elapsed:.2f} sec")


# ---------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def ensure_dir(path):
    Path(path).mkdir(parents=True, exist_ok=True)


def export_latex_table(df, path, caption="GKT baseline results.", label="tab:gkt_results"):
    tex = df.to_latex(index=False, escape=False)

    tex = tex.replace(
        "\\begin{tabular}",
        f"\\begin{{table}}[t]\n"
        f"\\centering\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        f"\\begin{{tabular}}"
    )

    tex = tex.replace(
        "\\end{tabular}",
        "\\end{tabular}\n\\end{table}"
    )

    with open(path, "w", encoding="utf-8") as f:
        f.write(tex)


# ---------------------------------------------------------------------
# Data Loading
# ---------------------------------------------------------------------

def load_split(train_path, test_path):
    train = pd.read_csv(train_path, low_memory=False)
    test = pd.read_csv(test_path, low_memory=False)

    required = ["user_id", "skill_id", "correct", "timestamp"]

    for col in required:
        if col not in train.columns:
            raise ValueError(f"Missing column in train file: {col}")
        if col not in test.columns:
            raise ValueError(f"Missing column in test file: {col}")

    train = train[required].copy()
    test = test[required].copy()

    train["user_id"] = train["user_id"].astype(str)
    test["user_id"] = test["user_id"].astype(str)

    train["skill_id"] = train["skill_id"].astype(str)
    test["skill_id"] = test["skill_id"].astype(str)

    train["correct"] = pd.to_numeric(train["correct"], errors="coerce")
    test["correct"] = pd.to_numeric(test["correct"], errors="coerce")

    train = train[train["correct"].isin([0, 1])].copy()
    test = test[test["correct"].isin([0, 1])].copy()

    train["correct"] = train["correct"].astype(int)
    test["correct"] = test["correct"].astype(int)

    train = train.sort_values(["user_id", "timestamp"]).reset_index(drop=True)
    test = test.sort_values(["user_id", "timestamp"]).reset_index(drop=True)

    return train, test


def clean_skill_data(train, test):
    bad = {"unknown", "nan", "none", "", "null", "na"}

    train = train[~train["skill_id"].str.lower().isin(bad)].copy()
    test = test[~test["skill_id"].str.lower().isin(bad)].copy()

    train_skills = sorted(train["skill_id"].unique())
    skill_to_idx = {s: i for i, s in enumerate(train_skills)}

    train = train[train["skill_id"].isin(skill_to_idx)].copy()
    test = test[test["skill_id"].isin(skill_to_idx)].copy()

    train["skill_idx"] = train["skill_id"].map(skill_to_idx).astype(int)
    test["skill_idx"] = test["skill_id"].map(skill_to_idx).astype(int)

    return train, test, skill_to_idx


# ---------------------------------------------------------------------
# Skill Graph Construction
# ---------------------------------------------------------------------

def build_skill_adjacency(train, num_skills, undirected=True):
    transition_counts = Counter()

    for _, group in train.groupby("user_id", sort=False):
        skills = group.sort_values("timestamp")["skill_idx"].tolist()

        for a, b in zip(skills[:-1], skills[1:]):
            if a != b:
                transition_counts[(a, b)] += 1

    A = np.zeros((num_skills, num_skills), dtype=np.float32)

    for (a, b), count in transition_counts.items():
        A[a, b] += count

        if undirected:
            A[b, a] += count

    # Add self loops
    A += np.eye(num_skills, dtype=np.float32)

    # Row-normalize
    row_sum = A.sum(axis=1, keepdims=True)
    row_sum[row_sum == 0] = 1.0
    A = A / row_sum

    return A


# ---------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------

class GKTDataset(Dataset):
    def __init__(self, df, max_seq_len=100):
        self.samples = []
        self.max_seq_len = max_seq_len

        user_groups = list(df.groupby("user_id", sort=False))

        for _, group in tqdm(
            user_groups,
            total=len(user_groups),
            desc="Building GKT sequences",
            dynamic_ncols=True
        ):
            group = group.sort_values("timestamp")

            skills = group["skill_idx"].astype(int).tolist()
            corrects = group["correct"].astype(int).tolist()

            if len(skills) < 3:
                continue

            for start in range(0, len(skills) - 1, max_seq_len):
                s_chunk = skills[start:start + max_seq_len + 1]
                c_chunk = corrects[start:start + max_seq_len + 1]

                if len(s_chunk) >= 3:
                    self.samples.append((s_chunk, c_chunk))

        LOGGER.info(f"Created GKT sequences: {len(self.samples)}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        skills, corrects = self.samples[idx]

        x_skills = skills[:-1]
        x_corrects = corrects[:-1]
        y_skills = skills[1:]
        y_corrects = corrects[1:]

        L = min(len(x_skills), self.max_seq_len)

        x_skill = np.zeros(self.max_seq_len, dtype=np.int64)
        x_correct = np.zeros(self.max_seq_len, dtype=np.int64)
        y_skill = np.zeros(self.max_seq_len, dtype=np.int64)
        y = np.zeros(self.max_seq_len, dtype=np.float32)
        mask = np.zeros(self.max_seq_len, dtype=np.float32)

        x_skill[:L] = x_skills[:L]
        x_correct[:L] = x_corrects[:L]
        y_skill[:L] = y_skills[:L]
        y[:L] = y_corrects[:L]
        mask[:L] = 1.0

        return (
            torch.tensor(x_skill, dtype=torch.long),
            torch.tensor(x_correct, dtype=torch.long),
            torch.tensor(y_skill, dtype=torch.long),
            torch.tensor(y, dtype=torch.float32),
            torch.tensor(mask, dtype=torch.float32),
        )


# ---------------------------------------------------------------------
# GKT Model
# ---------------------------------------------------------------------

class GKTModel(nn.Module):
    def __init__(
        self,
        num_skills,
        adjacency,
        emb_dim=128,
        hidden_dim=128,
        dropout=0.2
    ):
        super().__init__()

        self.num_skills = num_skills
        self.hidden_dim = hidden_dim

        self.register_buffer(
            "adjacency",
            torch.tensor(adjacency, dtype=torch.float32)
        )

        self.input_embedding = nn.Embedding(
            num_embeddings=2 * num_skills,
            embedding_dim=emb_dim
        )

        self.input_proj = nn.Linear(emb_dim, hidden_dim)

        self.gru_cell = nn.GRUCell(
            input_size=hidden_dim,
            hidden_size=hidden_dim
        )

        self.graph_proj = nn.Linear(hidden_dim, hidden_dim)

        self.gate = nn.Parameter(torch.tensor(0.5))

        self.layer_norm = nn.LayerNorm(hidden_dim)

        self.dropout = nn.Dropout(dropout)

        self.output = nn.Linear(hidden_dim, 1)

    def forward(self, x_skill, x_correct, y_skill):
        """
        x_skill:   [B, T]
        x_correct: [B, T]
        y_skill:   [B, T]

        Returns:
        logits: [B, T]
        """

        B, T = x_skill.shape
        device = x_skill.device

        # Hidden state for each skill node
        h = torch.zeros(
            B,
            self.num_skills,
            self.hidden_dim,
            device=device
        )

        logits_steps = []

        for t in range(T):
            s_t = x_skill[:, t]
            c_t = x_correct[:, t]

            token = s_t + self.num_skills * c_t

            x_emb = self.input_embedding(token)
            x_in = torch.tanh(self.input_proj(x_emb))

            # Gather current skill state
            h_current = h[torch.arange(B, device=device), s_t]

            # Update observed skill state using GRU
            h_updated = self.gru_cell(x_in, h_current)

            h = h.clone()
            h[torch.arange(B, device=device), s_t] = h_updated

            # Graph propagation across skill graph
            msg = torch.einsum("ij,bjd->bid", self.adjacency, h)
            msg = torch.tanh(self.graph_proj(msg))

            h = self.layer_norm(
                h + torch.sigmoid(self.gate) * self.dropout(msg)
            )

            # Predict correctness for next skill
            q_next = y_skill[:, t]
            h_next = h[torch.arange(B, device=device), q_next]

            logit = self.output(h_next).squeeze(-1)
            logits_steps.append(logit)

        logits = torch.stack(logits_steps, dim=1)

        return logits


# ---------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------

def compute_metrics(y_true, y_prob):
    y_true = np.asarray(y_true).astype(int)
    y_prob = np.asarray(y_prob).astype(float)

    valid = np.isfinite(y_prob)

    y_true = y_true[valid]
    y_prob = y_prob[valid]

    y_prob = np.clip(y_prob, 1e-6, 1.0 - 1e-6)

    y_pred = (y_prob >= 0.5).astype(int)

    if len(np.unique(y_true)) < 2:
        auc = np.nan
    else:
        auc = roc_auc_score(y_true, y_prob)

    return {
        "Model": "GKT",
        "AUC": auc,
        "Accuracy": accuracy_score(y_true, y_pred),
        "LogLoss": log_loss(y_true, y_prob, labels=[0, 1]),
        "Brier": brier_score_loss(y_true, y_prob),
        "N": len(y_true),
    }


# ---------------------------------------------------------------------
# Training and Evaluation
# ---------------------------------------------------------------------

def train_one_epoch(model, loader, optimizer, scaler, loss_fn, device, use_amp):
    model.train()

    losses = []

    progress = tqdm(
        loader,
        desc="Training GKT",
        leave=True,
        dynamic_ncols=True
    )

    for x_skill, x_correct, y_skill, y, mask in progress:
        x_skill = x_skill.to(device, non_blocking=True)
        x_correct = x_correct.to(device, non_blocking=True)
        y_skill = y_skill.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)
        mask = mask.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.cuda.amp.autocast(enabled=use_amp and device.type == "cuda"):
            logits = model(x_skill, x_correct, y_skill)
            loss_raw = loss_fn(logits, y)
            loss = (loss_raw * mask).sum() / mask.sum().clamp_min(1.0)

        scaler.scale(loss).backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)

        scaler.step(optimizer)
        scaler.update()

        losses.append(loss.item())

        progress.set_postfix({
            "loss": f"{np.mean(losses):.4f}"
        })

    return float(np.mean(losses))


@torch.no_grad()
def evaluate(model, loader, device, return_predictions=False):
    model.eval()

    y_true = []
    y_prob = []

    progress = tqdm(
        loader,
        desc="Evaluating GKT",
        leave=True,
        dynamic_ncols=True
    )

    for x_skill, x_correct, y_skill, y, mask in progress:
        x_skill = x_skill.to(device, non_blocking=True)
        x_correct = x_correct.to(device, non_blocking=True)
        y_skill = y_skill.to(device, non_blocking=True)

        logits = model(x_skill, x_correct, y_skill)
        prob = torch.sigmoid(logits).detach().cpu().numpy()

        y_np = y.numpy()
        mask_np = mask.numpy().astype(bool)

        y_true.extend(y_np[mask_np].tolist())
        y_prob.extend(prob[mask_np].tolist())

    metrics = compute_metrics(y_true, y_prob)

    if not return_predictions:
        return metrics, pd.DataFrame()

    pred_df = pd.DataFrame({
        "model": "GKT",
        "correct": np.asarray(y_true, dtype=int),
        "p_correct": np.asarray(y_prob, dtype=float),
    })

    return metrics, pred_df


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("--train", required=True)
    parser.add_argument("--test", required=True)
    parser.add_argument("--out", default="results/gkt_final")

    parser.add_argument("--max_seq_len", type=int, default=100)
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--epochs", type=int, default=30)

    parser.add_argument("--emb_dim", type=int, default=128)
    parser.add_argument("--hidden_dim", type=int, default=128)
    parser.add_argument("--dropout", type=float, default=0.2)

    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight_decay", type=float, default=1e-5)

    parser.add_argument("--num_workers", type=int, default=4)

    parser.add_argument("--amp", action="store_true")
    parser.add_argument("--compile", action="store_true")
    parser.add_argument("--directed", action="store_true")

    parser.add_argument("--seed", type=int, default=42)

    args = parser.parse_args()

    global LOGGER
    LOGGER = setup_logger(args.out)

    ensure_dir(args.out)
    set_seed(args.seed)

    LOGGER.info("=" * 80)
    LOGGER.info("Running GKT baseline")
    LOGGER.info("=" * 80)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    LOGGER.info(f"Device: {device}")

    if device.type == "cuda":
        LOGGER.info(f"GPU: {torch.cuda.get_device_name(0)}")

    with Timer("Loading train-test split"):
        train_df, test_df = load_split(args.train, args.test)

    with Timer("Cleaning skill data"):
        train_df, test_df, skill_to_idx = clean_skill_data(train_df, test_df)

    LOGGER.info(f"Train interactions: {len(train_df)}")
    LOGGER.info(f"Test interactions: {len(test_df)}")
    LOGGER.info(f"Number of skills: {len(skill_to_idx)}")

    with Timer("Building skill transition graph"):
        adjacency = build_skill_adjacency(
            train_df,
            num_skills=len(skill_to_idx),
            undirected=not args.directed
        )

    np.save(Path(args.out) / "skill_adjacency.npy", adjacency)

    pd.DataFrame(
        {"skill_id": list(skill_to_idx.keys()), "skill_idx": list(skill_to_idx.values())}
    ).to_csv(Path(args.out) / "skill_mapping.csv", index=False)

    with Timer("Building train dataset"):
        train_dataset = GKTDataset(
            train_df,
            max_seq_len=args.max_seq_len
        )

    with Timer("Building test dataset"):
        test_dataset = GKTDataset(
            test_df,
            max_seq_len=args.max_seq_len
        )

    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=(device.type == "cuda"),
        persistent_workers=args.num_workers > 0
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=(device.type == "cuda"),
        persistent_workers=args.num_workers > 0
    )

    model = GKTModel(
        num_skills=len(skill_to_idx),
        adjacency=adjacency,
        emb_dim=args.emb_dim,
        hidden_dim=args.hidden_dim,
        dropout=args.dropout
    ).to(device)

    if args.compile and hasattr(torch, "compile"):
        LOGGER.info("Compiling model using torch.compile()")
        model = torch.compile(model)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay
    )

    scaler = torch.cuda.amp.GradScaler(
        enabled=args.amp and device.type == "cuda"
    )

    loss_fn = nn.BCEWithLogitsLoss(reduction="none")

    all_epoch_metrics = []
    best_auc = -1.0
    best_metrics = None
    last_pred_df = pd.DataFrame()

    for epoch in range(1, args.epochs + 1):
        LOGGER.info(f"Epoch {epoch}/{args.epochs}")

        with Timer(f"Training epoch {epoch}"):
            train_loss = train_one_epoch(
                model,
                train_loader,
                optimizer,
                scaler,
                loss_fn,
                device,
                use_amp=args.amp
            )

        with Timer(f"Evaluating epoch {epoch}"):
            metrics, pred_df = evaluate(
                model,
                test_loader,
                device,
                return_predictions=True
            )
            last_pred_df = pred_df

        metrics["Epoch"] = epoch
        metrics["TrainLoss"] = train_loss

        all_epoch_metrics.append(metrics)

        LOGGER.info(f"Epoch {epoch} metrics: {metrics}")

        if not np.isnan(metrics["AUC"]) and metrics["AUC"] > best_auc:
            best_auc = metrics["AUC"]
            best_metrics = metrics.copy()

            torch.save(
                {
                    "model_state_dict": model.state_dict(),
                    "skill_to_idx": skill_to_idx,
                    "args": vars(args),
                    "metrics": best_metrics,
                },
                Path(args.out) / "best_gkt_model.pt"
            )

            LOGGER.info(f"Saved best GKT model at epoch {epoch} with AUC={best_auc:.4f}")
            pred_df.to_csv(Path(args.out) / "gkt_predictions.csv", index=False)

    if best_metrics is None:
        best_metrics = all_epoch_metrics[-1]

    if not (Path(args.out) / "gkt_predictions.csv").exists() and len(last_pred_df):
        last_pred_df.to_csv(Path(args.out) / "gkt_predictions.csv", index=False)

    epoch_df = pd.DataFrame(all_epoch_metrics)
    epoch_df.to_csv(Path(args.out) / "gkt_epoch_metrics.csv", index=False)

    result_df = pd.DataFrame([best_metrics])
    result_df.to_csv(Path(args.out) / "gkt_metrics.csv", index=False)

    export_latex_table(
        result_df,
        Path(args.out) / "table_gkt.tex",
        caption="GKT baseline results.",
        label="tab:gkt_results"
    )

    LOGGER.info("Final best GKT metrics:")
    LOGGER.info("\n" + result_df.to_string(index=False))


if __name__ == "__main__":
    main()
